### ISSUE TITLE
Zarovnat tlačítka?

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/python.cz#115]
> posielala som jednej babe odkaz na stránku, nechcete tie buttony dole zarovnať? či to bolo zámerom? lebo zarovnané to vyzerá tak symetricky
> -- @SvetlanaM

![buttony](https://cloud.githubusercontent.com/assets/283441/14292143/0ee05c06-fb67-11e5-9ae6-1cb427c00168.png)

**Comment by SvetlanaM** [comment]
Pridala som   v https://github.com/pyvec/python.cz/pull/118/commits/0823edee0db4c914ae6de0db18348bd1d2112b3e vysku nech su stale zarovnane

**Comment by SvetlanaM** [comment]
Ako to vyzera?

**Comment by honzajavorek** [comment]
Bude to responsive, jo?

**Comment by honzajavorek** [comment]
Mergnul jsem to. Kdyby něco, pošli PR, už se to budu snažit mergovat :)
