### ISSUE TITLE
K diskuzi: gitter.im misto slacku

### ISSUE THREAD

**Issue by Visgean** [pyvec/python.cz#134]
Na IRC jsem zminoval ze by bylo rozumenjsi pouzivat gitter.im misto slacku - da se tam prihlasit bez accountu a funguje na github prihlaseni

---

Edit [@encukou]: Z diskuze vyplynuly dvě věci co je potřeba udělat:

* [ ] Spustit appku na auto-invites
* [ ] Jasně někde zdokumentovat, že to jde použít i jako IRC/XMPP (aspoň malým linkem)

**Comment by honzajavorek** [comment]
Problém je, že lidi, kteří znají Slack a používají ho už třeba v práci, chtějí používat Slack. Máme Gitter na [Dreddu](https://github.com/apiaryio/dredd), ale na Slack nám leze víc lidí, takže asi přejdeme na něj ¯\\\_(ツ)\_/¯

Přejít na Gitter by znamenalo zmigrovat (opět) všechny lidi, integrace, atd. Zase chápu, že Gitter je přístupnější přes GitHub login.

Já to chtěl vyřešit tak, jak to máme na [API Blueprintu](https://github.com/apiaryio/api-blueprint/), tzn. že se rozběhne nějaká jednoduchá appka, která udělá auto-invites. Založil jsem si na to https://github.com/pyvec/cz.pycon.org-2016/issues/46

**Comment by Visgean** [comment]
Mas asi pravdu, ze pro urcitou cast lidi ta pristupnost uz je presne naopak, asi to skutecne neni potrebne, jen me stve, ze OS komunita se upira k proprietarni firme...

**Comment by benabraham** [comment]
Na druhou stranu to není nějakej vendor lock-in, ale pitomej chat, kterej se dá za pár dní přesunout jinam. Třeba na gitter.im, kterej ale taky není žádný svobodný řešení.

**Comment by Visgean** [comment]
j, ale gitter ma alespon oficialni transport na irc...

**Comment by encukou** [comment]
On 08/15/2016 11:30 PM, Visgean Skeloru wrote:
> j, ale gitter ma alespon oficialni transport na irc...

To má Slack taky, jinak bych na něm nebyl.

https://get.slack.help/hc/en-us/articles/201727913-Connecting-to-Slack-over-IRC-and-XMPP

**Comment by honzajavorek** [comment]
Takže za mě z toho zatím vychází jako kompromis:

- Spustit appku na auto-invites
- Jasně někde zdokumentovat, že to jde použít i jako IRC/XMPP (aspoň malým linkem)

**Comment by hroncok** [comment]
Koukali jste na https://www.mattermost.org/?

**Comment by Visgean** [comment]
no to uz je asi jedno jestli mattermost nebo gitter... no nic, tohle se uz asi muze zavrit, ne? nebo to mam repostnout k :fire: plamene diskuzi na fb?

**Comment by honzajavorek** [comment]
Nech prosím otevřeno, rád bych aspoň udělal ty dvě věci, co jsem zmínil
nahoře.

**Comment by Sanqui** [comment]
Další (poměrně ambiciozní) otevřenou možností je http://matrix.org/.

**Comment by honzajavorek** [comment]
Zavírám ve prospěch https://github.com/pyvec/zapojse/issues/51.
