### ISSUE TITLE
Odkaz na GitHub nefunguje pro nepřihlášené

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/python.cz#150]
Tak prej odkaz https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+org%3Apyvec vede na 404, když člověk není přihlášený na GitHubu. Což je blbý, protože pak to vypadá jako chyba, ne jako že se máš přihlásit nebo si udělat účet.

To bude asi platit i na ty odkazy v patičce "upravit tuto stránku", ale nezkoušel jsem, nevím.

**Comment by kvbik** [comment]
this issue is closed, but new version is still not up and running ;)

if you'd like to add better url, that works for *non-github-logged-in* users, here [1] you are

[1] https://github.com/search?utf8=%E2%9C%93&q=org%3Apyvec+org%3Apyladiescz+state%3Aopen&type=Issues

**Comment by encukou** [comment]
Yeah, I had to revert the fix :(
Honza's solution is very nice, we just need to deploy it properly.
