### ISSUE TITLE
Z odkazu na Github se nedá přidat nový issue

### ISSUE THREAD

**Issue by encukou** [pyvec/python.cz#151]
[Odkaz](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+org%3Apyvec) vede na hledání, kde není tlačítko New issue.

**Comment by honzajavorek** [comment]
No není to ideální, viz https://github.com/pyvec/python.cz/issues/150. Lepší by asi bylo mít stránku, která teprve vede na ty issues (i na issues organizace `pyladiescz` třeba a má tlačítko na [vytvoření nového issue](https://github.com/pyvec/zapojse/issues/new).

A ta stránka by měla být spíš na pyvec.org než na python.cz.
