### ISSUE TITLE
Odkaz na manuál pro pořadatele srazů/kurzů někam zmizel

### ISSUE THREAD

**Issue by zuzejk** [pyvec/python.cz#152]
Nevím, jak to bylo původně, ale nepodařilo se mi nikde najít odkaz na ty manuály...

**Comment by lspdv** [comment]
nezmizel. neni tam vubec. ja udelala PR a pridala to tam a nikdo se nema k tomu to schvalit odmitnout. :-)

**Comment by encukou** [comment]
Už je tam! Omlouvám se že to PR takhle zapadlo 😢

**Comment by lspdv** [comment]
Tak hlavne ze to tam je :-) dik

Dne pondělí 28. listopadu 2016 Petr Viktorin <notifications@github.com>
napsal(a):
