### ISSUE TITLE
Doladit seznam úkolů

### ISSUE THREAD

**Issue by encukou** [pyvec/python.cz#170]
* [x] Pull Request https://github.com/pyvec/python.cz/pull/169 přidává seznam úkolů, ale při každém přístupu se znovu ptá Githubu, na data. Pokud se na tu stránku podívá víc než 15 lidí za minutu, Github odmítne přístup a stránka se nezobrazí.
* [ ] Stránka říká že máme o úkolech hlasovat, ale neukáže počet hlasů
* [ ] Možná by bylo dobré přidat některé tagy (třeba tenhle úkol má `petr-will-coach`, t.j. odchytni si mě na sprintu nebo hands-on srazu, a pomůžu ti s ním)
* [x] Jo, a něco je špatně s nastavením serveru

**Comment by honzajavorek** [comment]
Na to s tím labelem jsem udělal https://github.com/pyvec/python.cz/issues/185, to druhé mám připravené, pošlu PR.
