### ISSUE TITLE
Napsat test, který bude hlídat, aby firmy nebyly v Jemenu

### ISSUE THREAD

**Issue by messa** [pyvec/python.cz#172]
Na stránce: http://python.cz/prace/

Ale ať do toho geojsonu koukám jak koukám, netuším proč.

**Comment by messa** [comment]
A nejsou sami, evidentně od Epamu zkopírovali prohozené `coordinates` :)

**Comment by honzajavorek** [comment]
Jo, to je klasická chyba, jak je něco v Jemenu a má to být v ČR, tak je to vždycky prohozené latitude a longitude :) Poslal bys prosím PR s opravou?

**Comment by honzajavorek** [comment]
Ještě mě napadlo napsat test ([něco jako tento](https://github.com/pyvec/python.cz/blob/master/tests/valid_json_test.py)), který by načetl ten geojson a zkontroloval by, jestli latitude a longitude neujíždějí aspoň někam mimo Evropu.

**Comment by honzajavorek** [comment]
A obávám se, že podobný problém bude tady: https://github.com/pyvec/python.cz/pull/171 Když to zadám do Google, vyjede mi nějaký oceán. Když to prohodím, vyjede mi Radlická :)

**Comment by honzajavorek** [comment]
Tak ne! Ha! geojson to očividně prostě má naopak než Google Maps. Interesting.

**Comment by honzajavorek** [comment]
Opraveno díky @thejoeejoee v #174, ale já bych stejně ještě napsal ten test :)
