### ISSUE TITLE
Když se Zapojse dotáže GitHub API a request selže, mohlo by se s tím vypořádat

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/python.cz#191]
- přeskočit issue?
- nezobrazit issues a místo toho nějakou pěknou hlášku se smutným hadem (viz https://github.com/pyvec/zapojse/issues/48), že issues se nepovedlo načíst a ať jdou lidi aspoň na pyvec/zapojse na GitHubu

**Comment by encukou** [comment]
Neaktualizovat cache a ukazat stara data?

**Comment by honzajavorek** [comment]
To by asi šlo :) Krom případu, kdy nemáš ještě tu cache :D A taky myslím, že ta cache je časově omezená, nemaže se ručně, ale to by asi šlo prostě prodloužit tu platnost. Musel bych se podívat, co všechno umožňuje. Každopádně dobrý nápad. Ten případ před první keší nebude těžké ošetřit.

**Comment by honzajavorek** [comment]
To mě jinak přivádí na myšlenku, že cache by se měla asi mazat při deployi, pokud se nemaže.

**Comment by honzajavorek** [comment]
OK, [maže](https://github.com/pyvec/python.cz/blob/master/deployment/update.sh#L18) :)
