### ISSUE TITLE
Vysvětlit, k čemu je GITHUB_TOKEN

### ISSUE THREAD

**Issue by messa** [pyvec/python.cz#202]
V readme - jestli je to opravdu životně důležité to nastavovat pro lokální vývoj, a k čemu se to používá.

**Comment by honzajavorek** [comment]
K tomu, aby jelo zapojse, které stahuje informace přes GitHub API.

**Comment by messa** [comment]
Nakonec jsem stejně zjistil, že python.cz != pyvo.cz :)

Jinak když na to lezu přes localhost, tak to vrací 404, protože je to nakonfigurované na 0.0.0.0. Asi by se taky mohlo zmínit v readme. (Tohle issue jsou jen takové poznámky, třeba se jednoho dne objeví PR :smiley: )

**Comment by honzajavorek** [comment]
Díky, já to tak beru. Třeba to někdo na sprintu vylepší, nebo si tady toho všimne a pošle PR, přesně jak píšeš :)
