### ISSUE TITLE
Zapojse hází 502 Bad Gateway

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/python.cz#205]
Proste stále trvá moc dlouho načíst všechny issues i po úpravách od @hroncok :cry: Stránka je nepoužitelná.

**Comment by hroncok** [comment]
Hodí mi to po 3 vteřinách 502. Určitě je to dlouhým načítáním?

**Comment by hroncok** [comment]
Nedalo by se to cronem pouštět na roští jako funkce, ať si to ta data prostě cachuje, nechat platnost cache třeba na celý den a vždy v noci to invalidovat a trigrnout? Not ideal, ale...

**Comment by honzajavorek** [comment]
Funguje! Opraveno ve #207.
