### ISSUE TITLE
Vytvořit stránku pro pracovní nabídky

### ISSUE THREAD

**Issue by messa** [pyvec/python.cz#209]
Ideálně i označovat nabídky vhodné pro juniory.
Nápad ze Slacku.

**Comment by messa** [comment]
btw. https://github.com/pyvec/zapojse/issues/35

**Comment by zuzejk** [comment]
ideálně aby se to dalo třeba nějak odebírat

**Comment by honzajavorek** [comment]
Closes https://github.com/pyvec/python.cz/issues/99

**Comment by honzajavorek** [comment]
Vysvětlení, proč to tu zavírám, je zde: https://github.com/pyvec/zapojse/issues/35#issuecomment-325124547
