### ISSUE TITLE
Zrušit runserver.py a SERVER_NAME

### ISSUE THREAD

**Issue by messa** [pyvec/python.cz#215]
Ahoj,

navrhuju zrušit runserver.py (https://github.com/pyvec/python.cz/blob/ba41e40ecc0291ee22a0e531dd8a72613f9b815f/runserver.py) a v README to doporučit spouštět "normálně" přes flask run. Co si o tom myslíte?

Proč se hýbe se SERVER_NAME? Potom na lokále musím zadávat opravdu doslova "localhost".

**Comment by encukou** [comment]
Jestli se to tak udělá, můžeš přidat `runserver.sh` (nebo třeba `debugserver.sh`), který nastaví `FLASK_APP` a pustí flask v debug režimu a reloaderem? (Pokud teda Flask stále `FLASK_APP` potřebuje)

**Comment by honzajavorek** [comment]
Já jsem pro, aby se zupgradovalo na nejnovější Flask a dělaly se věci tak, jak je doporučeno v jeho dokumentaci, takže `runserver.py` klidně zruším. Na druhou stranu, taky se mi moc nelíbí, že bude potřeba mít nějakou env var. Nicméně stejně už je potřeba `GITHUB_TOKEN` a já osobně si ty env vars nastavím přes [direnv](https://github.com/direnv/direnv), tak je mi to fuk...

S tím `SERVER_NAME` bych chtěl nejdříve zapátrat v historii, proč se s tím hýbalo.

**Comment by honzajavorek** [comment]
`SERVER_NAME` je kvůli přesměrovávání z www, nemůžeme ho odebrat: https://github.com/pyvec/python.cz/pull/183/files

**Comment by messa** [comment]
Bylo by super, kdyby to šlo řešit nějak jinak. Aspoň kdyby stačilo SERVER_NAME nastavovat jen při deploymentu na python.cz. Třeba nastavit nějakou env proměnnou a na jejím základě by si webovka sama SERVER_NAME nastavila.
