### ISSUE TITLE
Stránka, která bude agregovat události

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/python.cz#220]
Rozhodli jsme se pro federaci místo centralizace. Jednotlivé události se budou prezentovat lidem kde budou chtít (pyvo.cz, meetup.com, Facebook, ...) a na python.cz bude stránka, která bude všechny eventy agregovat. Tím bude centrální místo a zároveň se bude moci zapojit úplně kdokoliv se svým `.ical` souborem nebo Google kalendářem.

Myšlenka je taková, že bude YAML soubor, kde bude seznam `.ical` exportů a stránka bude všechny skládat dohromady, vyexportuje globální `.ical` pro Python komunitu a zároveň vyrenderuje stránku, kde budou nadcházející události.

**Comment by honzajavorek** [comment]
Mluvil jsem o tom s @miiila a říkal, že by to rád vytvořil. Rád by si na něčem takovém vyzkoušel Python a Open Source a třeba i spolupráci se mnou. Dohodli jsme se na nějakém postupu a že pokud si na to do měsíce nenajde čas, tak to necháme někomu jinému. Ještě pak upravím popis issue, aby bylo jasné, co se přesně bude dělat.

**Comment by honzajavorek** [comment]
Tak @miiila si na to čas zatím neudělal. Pokud se ozve někdo jiný, rád mu s tím pomůžu.

**Comment by honzajavorek** [comment]
Vypadá to, že @mikicz by se na to podíval. Pokud by se tak stalo, @messa by se možná mohl podívat na https://github.com/pyvec/pyworking.cz/issues/1, co? *mrk mrk*

**Comment by messa** [comment]
Pyworking ical export nasazen :rocket: 

- workshopy: https://pyworking.cz/workshops.ics
- sessions: http://api.meetup.com/pyworking/upcoming.ical
