### ISSUE TITLE
Přidat Olomouc

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/python.cz#235]
Na úvodní stránce není Pyvo v Olomouci.

**Comment by frenzymadness** [comment]
Ještě není ani na Pyvo.cz protože https://github.com/pyvec/pyvo.cz/pull/65 a https://github.com/pyvec/pyvo.cz/pull/64

Čeká se na merge toho prvního a pak dotáhnu i to druhé.

**Comment by encukou** [comment]
Už to je na pyvo.cz.

**Comment by fivaldi** [comment]
Převezmu to a udělám PR pro úvodní stránku...
