### ISSUE TITLE
Development docs are outdated

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/python.cz#277]
I think after switching to Elsa this https://github.com/pyvec/python.cz#development is not true anymore.

**Comment by hroncok** [comment]
what's wrong there?

**Comment by honzajavorek** [comment]
Shouldn't it be Elsa's `serve`? Well if we migrate to pipenv, then I guess `pipenv run serve`

**Comment by hroncok** [comment]
It's Elsas's `--help`.

**Comment by honzajavorek** [comment]
Oh, sorry, I overlooked it yesterday 🤦‍♂️
