### ISSUE TITLE
Pyvo mugs are not aligned vertically

### ISSUE THREAD

**Issue by hroncok** [pyvec/python.cz#281]
![pullitry](https://user-images.githubusercontent.com/2401856/45594771-7db94580-b9a0-11e8-855e-0ebbc22c6035.png)

(This is after https://github.com/pyvec/python.cz/pull/280.)

**Comment by Aprillion** [comment]
@hroncok - asi mozme zavret issue ako "Not Reproducible" :D
<img width="1247" alt="2022" src="https://user-images.githubusercontent.com/1087670/187032282-ca994a90-951a-4b81-b65c-85492194a27b.png">
