### ISSUE TITLE
Rozložení srazů na mobilu

### ISSUE THREAD

**Issue by mikicz** [pyvec/python.cz#283]
Na menších obrazovkách se některé názvy srazů překrývají s ikonou.
![screenshot_2018-09-16-19-02-49-309_com android chrome](https://user-images.githubusercontent.com/5583319/45598932-7b2c0f80-b9e3-11e8-9b43-a3cdebea473c.png)

**Comment by mikicz** [comment]
A koukám že jsou i jinak velké

**Comment by encukou** [comment]
This was fixed in https://github.com/pyvec/python.cz/pull/294
