### ISSUE TITLE
Nevidím eventy z Google Kalendáře

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/python.cz#289]
Přidal jsem tam Hadí workshop a nevidím ho na webu na https://python.cz/akce/. Přitom jsem to dělal už nějaký den zpátky.

<img width="599" alt="image" src="https://user-images.githubusercontent.com/283441/46040834-a31d2080-c111-11e8-867c-3492569687ac.png">

**Comment by mikicz** [comment]
Hele co koukám do historie buildů na Travis tak poslední successful build byl před dvěma dněma, ten dnešní failnul před patnácti minutama. Jak je ten cron nastavený? Třeba tam úplně chybí build `3 days ago` a `yesterday`...

https://travis-ci.org/pyvec/python.cz/builds

**Comment by hroncok** [comment]
Runs daily
 Ran 20 minutes ago
 Scheduled in about 24 hours from now
 Do not run if there has been a build in the last 24h

**Comment by honzajavorek** [comment]
Tak to bude asi tim https://github.com/pyvec/python.cz/issues/287. Nezkoumal jsem, jen jsem si toho vsiml. Taky jsem mrkal jestli to sezere nejak to URL v popisu eventu, protoze v Google Calendar nejde zadat policko URL, je tam jen popis.

**Comment by mikicz** [comment]
(Pustil jsem build ručně, prošel a akce už tam je)

No myslím, že bude problém s tím `Do not run if there has been a build in the last 24h`. Pokud to bere fakt doslova, tak to vezme fakt 24 hodin ale build z předchozího dne proběhl v posledních 24 hodinách (protože trvá něco kolem minutu) -> build se udělá jednou za dva dny...

**Comment by honzajavorek** [comment]
Aha, lol... tak proste vypnem tu podminku.

**Comment by honzajavorek** [comment]
👍
