### ISSUE TITLE
Události z meetup.com

### ISSUE THREAD

**Issue by encukou** [pyvec/python.cz#557]
iCal z meetup.com už není veřejně dostupný.
Události  *PyWorking Sessions* a *PyData Prague* se tak na python.cz nezobrazují.

**Comment by honzajavorek** [comment]
Ok, tak jsem myslel, že #559 tohle vyřeší, ale dnes mi tatáž implementace přestala fungovat na junior.guru a když jsem to zkoumal, tak to vypadá, že meetup.com odebrali ze svého webu i poslední možnost, jak načíst jejich eventy strojově (json-dl metadata pro lepší SEO na Google) 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ Tahle služba je fakt opakem otevřeného internetu. Jak a jestli to někdy opravím, to teda nevím. Každopádně nevím, jestli je v mých silách udržovat dvě místa (junior.guru a python.cz), která se budou snažit dostat data z takto agresivní služby.
