### ISSUE TITLE
Zkratka jazyka místo zeměkoule u zdrojů pro začátečníky

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/python.cz#80]
https://twitter.com/mcbig_cz/status/676113365748588544

**Comment by encukou** [comment]
Nebo vlaječku :)

**Comment by honzajavorek** [comment]
Kterou? ;-) http://flagsarenotlanguages.com/

**Comment by encukou** [comment]
Americkou nebo britskou.
Veškerá argumentace na flagsarenotlanguages.com předpokládá že ukazuješ ty vlajky lidem, kteří dané jazyky znají a chtějí obsah ve svém jazyce. U nás oslovujeme lidi, kteří umí *česky*, a varujeme je že obsahu nemusí rozumět. Navíc to jsou začátečníci. Nemám usability study, ale předpokládal bych že vlajce porozumí víc lidí než zkratce [en]. A je jedno která vlajka to bude.

**Comment by messa** [comment]
Doporučuji podle obtížnosti: :gb: pro náročnější texty pro pokročilé, :us: pro návody pro začátečníky.

**Comment by encukou** [comment]
@messa: To ovšem nepochopí nikdo...

**Comment by honzajavorek** [comment]
To byl asi jen trolling aka traditional english and simplified english :)
Dame tam britskou, sme v evrope.

**Comment by encukou** [comment]
[Zeptal jsem se](http://flagsarenotlanguages.com/blog/2012/05/iconography-for-translations-best-practice-for-communicating-availability-of-translated-content/#comment-36977) člověka, co o těchhle věcech očividně přemýšlel. Zatím si přes mail vyžádal víc informací.

**Comment by Glutexo** [comment]
@encukou Odkaz už nepremáva. :(
