### ISSUE TITLE
Nápady na stránce "Zapoj se" se trochu rozsypávají

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/python.cz#82]
Obrázek napoví nejlépe:

<img width="1185" alt="screen shot 2015-12-30 at 09 59 14" src="https://cloud.githubusercontent.com/assets/283441/12048498/14e76ff4-aedc-11e5-9cf1-976a5fc9c256.png">

**Comment by martinbilek** [comment]
Zrovna jsem řešil podobný layout na jednom projektu. Možná řešení, co jsem objevil, jsou:
1. zafixovat napevno množství boxů na řádku (obalit je v `<div class="row"></div>`)
2. nastavit všem boxům fixní výšku
3. počítat podle velikosti okna prohlížeče, kolik se vejde boxů na řádku a podle toho je obalit v `<div class="row"></div>` (v Angularu je to relativně jednoduchá direktiva)

Myslím, že je pro účely Python.cz ideální varianta **1.**, tj. dát na každou řádku přesně 4 boxy, cca následovně by to mohlo vypadat:
```
<div class="row tasks">
    <div class="col-sm-3">...</div>
    <div class="col-sm-3">...</div>
    <div class="col-sm-3">...</div>
    <div class="col-sm-3">...</div>
</div>
<div class="row tasks">
    <div class="col-sm-3">...</div>
    <div class="col-sm-3">...</div>
    <div class="col-sm-3">...</div>
    <div class="col-sm-3">...</div>
</div>
...
...
...
```

**Comment by honzajavorek** [comment]
Teď se nekouknu do kódu, ale myslím, že něco jako 1 a možná i trochu 2 bych tam měl mít. Problém podle mě je, že úkol s virtuálními mašinami je moc vysoký a rozbije ostatní. Možná tam mám jen `min-height`?

**Comment by pstanisl** [comment]
Nedávno, když jsem něco podobného řešil, tak jsem použil ```flexbox``` u kterého se výška nastavovat nemusí. Samozřejmě to nebude fungovat ve starých prohlížečích, ale s novými prohlížeči je podpora dobrá, viz [caniuse](http://caniuse.com/#feat=flexbox). Neříkám, že je to optimální řešení, ale stojí za to ho zvážit.

První dva prvky mají stejnou výšku a třetí má jinou, protože se nemusí přizpůsobovat:

<img width="919" alt="screenshot 2016-03-03 22 34 00" src="https://cloud.githubusercontent.com/assets/1212845/13510543/49da43c0-e191-11e5-9199-fa7b512ade1d.png">

Po změně šířky se poslední prvek přizpůsobí:

<img width="1217" alt="screenshot 2016-03-03 22 34 12" src="https://cloud.githubusercontent.com/assets/1212845/13510547/4e9487a4-e191-11e5-9bc4-a19f886b639a.png">

**Comment by honzajavorek** [comment]
Díky všem za pokusy to opravit! Nicméně teď se Trello zrušilo ve prospěch GitHub issues, tak zavírám.
