### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by tomasbedrich** [pyvec/python.cz#92]
Není nakonfigurovaná HTTPS verze. Lze použít: https://letsencrypt.org/

**Comment by honzajavorek** [comment]
Na co je dobrá https verze pro vesměs statický web?

**Comment by encukou** [comment]
Na to, že si uživatel může být jistější že ten statický obsah je fakt od nás.

Na druhou stranu to znemožňuje HTTP cache (ale používá takovou věc v době Googlu někdo?)

**Comment by honzajavorek** [comment]
Hm. Já osobně myslím, že je to zbytečnost, ale klidně to udělejte. Peněz za
certifikát je podle mě škoda. Taky pamatujte, že doména není naše - nevím,
jestli to na to má vliv.

**Comment by tomasbedrich** [comment]
Taky bych za to neplatil, ale letsencrypt je zadarmo a celkem rychlý a jednoduchý. ;)

**Comment by encukou** [comment]
Jo, vypadá to jednoduše... https://gethttpsforfree.com/

**Comment by rbas** [comment]
Když vydržíte ještě nějakou dobu, bude u nás podpora LE přímo z administrace. Podpora je +/- napsaná. Jen to ještě nemáme nasazené a pořádně protestované.
_Podpora přímo v administraci bude mít tu výhodu, že se certifikáty budou automaticky prodlužovat._

**Comment by honzajavorek** [comment]
:+1:

**Comment by hroncok** [comment]
Používám CloudFare. Je to nasazené na 730ne.cz, mojefedora.cz, fedoralovespython.org, hroncok.cz. Je to zadarmo, používá to lets encrypt, naklikáš to za 5 minut. Stačí změnit NS. Výhoda je, že to funguje i na gh pages, openshiftu a jiných službách zdarma, kde to jinak nejde.

**Comment by frenzymadness** [comment]
Možno tím pádem nasadit i pro PyLadies.

https://github.com/PyLadiesCZ/pyladies.cz/issues/58

**Comment by honzajavorek** [comment]
@hroncok Kdysi mi kdosi říkal, že by s tím šlo vyřešit i přesměrování www, se kterým taky bojujem. Co je na tom pravdy?

**Comment by hroncok** [comment]
Ano, šlo.

Dne 25. 8. 2016 8:31 napsal uživatel "Honza Javorek" <
notifications@github.com>:

**Comment by michalwiglasz** [comment]
Vyresene HTTPS navic umoznuje pouzit HTTP2, coz muze (ale nemusi) znamenat trochu rychlejsi web.

**Comment by sairon** [comment]
Bavil jsem se o tom s @encukou na sprintu, který říkal, že čeká, až Roští udělá klikátko, což mělo být už před měsícem (http://blog.rosti.cz/lets-encrypt-uz-brzy/). S CloudFlare je problém ten, že je potřeba k nim přesunout celou zónu, což u python.cz udělat nejde, když není naše.

Jsou tu dvě další možnosti - buď nastavit HTTPS certifikát u Roští (to se mi ale nepodařilo zjistit, jak se teď "správně" dělá) nebo ten záznam v zóně poslat na nějakou reverzní proxy na jiném serveru, která bude dělat HTTPS. To ale znamená delší trubku od klienta k serveru (byť to to jsou fakticky jen nějaké milisekundy navíc).

A ještě tedy poznamenávám, že jak CloudFlare, tak řešení s reverzní proxy, znamená, že to šifrování nebude end-to-end a po nějakou dobu ta data budou putovat po internetu v plain textu. Sice je tady nějaký útok mnohem méně pravděpodobný, než když to je plain text až ke klientovi, kdy MitM může data podvrhnout mnohem snadněji. Jen by se na to nemělo zapomínat.

**Comment by hroncok** [comment]
Úplně plain text to být nemusí, CloudFare může komunikovat s hostingem přes self signed certifikát. Ale ano, úplně end to end encryption to nebude.

Nemůžem dát zónu ani po dohodě?

**Comment by rbas** [comment]
Zdravím pánové. Nasazení "klikátka" na https se zdrželo. Stálo nám ted v cestě příliš mnoho nečekaných provozních problémů. Pokud máte vlastní certifikát a není to LE tak vám ho můžeme nasadit ručně. 

Martin, Roští.cz

**Comment by sairon** [comment]
Výhodou self-signed certifikátu bude jen to, že mu můžeš nastavit neomezenou platnost a nemusíš řešit jeho obnovování co tři měsíce (což lze elegantně řešit třeba přes acme.sh nebo jiného LE klienta) nebo co rok (StartSSL). Pořád ale musíš mít možnost ho na serveru nasadit.

Pokud by nám pan @kubicek byl ochoten nastavit u domény NS na CloudFlare pod naší správou, usnadnilo by se tím víc věcí. Ale nevím, jestli tomu tak není i z toho důvodu, že chce s doménou nakládat i jinak, než nám tam přidávat záznamy pro projekty Pyvce :)

**Comment by honzajavorek** [comment]
Jestli bude klikatko (coz jsem nevedel), tak mi dava smysl pockat az bude
:) Zas tak critical to fakt neni.

Jinak neni problem nastavit domenu python.cz nekam jinam, uz pred casem
Rosti.cz menilo NS nebo co to menilo a nebyl problem to pres podporu
http://xnet.cz/ zmenit, s tim neni asi zadny problem. Ale ja se v tomhle
fakt uplne prd vyznam. Reknete mi, co mam napsat na support a ja to napisu,
ale strasne me nebavi resit cokoliv kolem HTTPS, NS, DNS, certifikatu
apod., takze se bez prinuceni asi nebudu uplne snazit to ve svym volnym
case nijak dobrovolne pochopit.


2016-08-25 9:25 GMT+02:00 Jan Čermák <notifications@github.com>:

**Comment by encukou** [comment]
Koukl jsem se teď do administrace u pyvo.cz, a klikátko tam bylo, tak jsem na to klikl. Firefox mi vynadal, že externí obrázků a Javascripty a CSS a fonty nejdou přes HTTPS, tak jsem to opravil – a už to jede!

https://pyvo.cz

**Comment by honzajavorek** [comment]
Takže zavíráme? Nechceš to naklikat i pro python.cz? :)

**Comment by encukou** [comment]
Rád s tím někomu pomůžu na některém sprintu, kde se objevím (např. PyCon CZ, čtvrtek v Nekavárně).

**Comment by lspdv** [comment]
@encukou co kdybys s tim pomohl mne na python.cz a ja to pak udelam cvicne pro pyladies.cz

**Comment by encukou** [comment]
Bohuzel se obe nastavuji jinak, python.cz je na Rosti ale pyladies.cz na
Github Pages :(


On Dec 20, 2016 8:47 PM, "Veronička" <notifications@github.com> wrote:

@encukou <https://github.com/encukou> co kdybys s tim pomohl mne na
python.cz a ja to pak udelam cvicne pro pyladies.cz

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/pyvec/python.cz/issues/92#issuecomment-268339951>, or mute
the thread

**Comment by encukou** [comment]
https://python.cz now works, using roští's wonderful one-click Letsencrypt certificate. #180 should fix mixed content issues.

**Comment by encukou** [comment]
Some mixed content is left at /prace and /en/jobs/ :(
Not closing yet.

**Comment by honzajavorek** [comment]
It's the map:

<img width="802" alt="image" src="https://cloud.githubusercontent.com/assets/283441/22106630/f2415dae-de49-11e6-93d6-02dfa1de1c95.png">
