### ISSUE TITLE
Náhled pro FB je hrozný

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/python.cz#94]
<img width="510" alt="screen shot 2016-02-26 at 15 21 29" src="https://cloud.githubusercontent.com/assets/283441/13354641/ac509562-dc9c-11e5-9762-c304b4536fac.png">

**Comment by messa** [comment]
Tyhle věci se dají debugovat tady: https://developers.facebook.com/tools/debug

Problémy jsou dva: URL v `og:image` není absolutní a směřuje na obrázek, jehož rozměry nejsou aspoň 200x200 px.

> Please define a chosen image using the og:image metatag, and use an image that's at least 200x200px and is accessible from Facebook. Image 'http://python.cz/static/images/logo-plain.png' will be used instead.

Zkusím s tím něco udělat.

**Comment by honzajavorek** [comment]
Vyřešeno ve #112 :heart: :tada: :cat:
