### ISSUE TITLE
Odstranit obří obrázky z historie repozitáře

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/python.cz#96]
Rebasnout historii a oddelat z ni obrovske obrazky co tam byly a uz ani nejsou (https://github.com/pyvec/python.cz/commit/e86388e510ab6ddd2b709d543726e9cbdcfd8b7b a dalsi), protože jsem je pak zmenšil.

**Comment by honzajavorek** [comment]
@encukou Vyvolavam te jakozto Git MacGyvera. Nevis jak by se tohle dalo co nejelegantneji udelat?

**Comment by encukou** [comment]
Pomocí [`git filter-branch`](https://git-scm.com/docs/git-filter-branch) ([GH návod](https://help.github.com/articles/remove-sensitive-data/)). Ale elegantní to teda moc není...

**Comment by kvbik** [comment]
elegantni to neni vubec, protoze se cela historie zmeni a jsou lidi (jako treba ja), kteri to nemaji moc radi. ale na druhou stranu hodne nemam rad velke soubory v git historii.. takze jsem rozpolceny.

btw, konecne jsem nasel clanek [1], kde nekdo sdili muj nazor na `rebase`!

[1] http://geekblog.oneandoneis2.org/index.php/2013/04/30/please-stay-away-from-rebase

**Comment by benabraham** [comment]
Rozměry, co tam jsou, jsou při dnešních 2× a 3× a nevím jakejch ultra rozlišeních, malý. O výřezech nemluvě. A metadatech…

Takže by bylo záhodno originály zachovat. Samozřejmě jsou větší problémy, ale pokud někoho napadne řešení, kde se vlk nažere a koza zůstane celá, tak sem s ním.

**Comment by encukou** [comment]
https://git-lfs.github.com/

**Comment by honzajavorek** [comment]
**Řešení historie:**

Prostě to rebasnu a vymažu z historie. Třeba u mě doma na pomalém internetu trvá clone tohoto repa asi 10 minut.

**Řešení budoucnosti:**

Mít Pyvec galerii fotek a tahat to rovnou z ní formou odkazů na soubory na Pyvcím Google Drive.

**Comment by honzajavorek** [comment]
Hm, tak ne, vyměkl jsem. Přepisování historie je fakt shit. Velký soubory jsou taky shit. Nevím co s tím. Asi nic. Poslal jsem aspoň https://github.com/pyvec/python.cz/pull/165.

**Comment by honzajavorek** [comment]
Helenc, já bych to asi dál prostě neřešil. Kdo má pomalý internet, udělá shallow clone. Kdo rychlý, bude mu to jedno. Rebasovat historii se mi nechce. LFS jsem zkoumal a vypadalo to jako experiment, na Roští by se to muselo spešl doplnit. Kdyby někoho něco ještě napadlo, dejte vědět.
