### ISSUE TITLE
Přesměrovávat www.python.cz na python.cz

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/python.cz#98]
Nastavit presmerovani z www... na apex domenu v `/srv/conf/nginx.d/` a zdokumentovat to. pyvo.cz vypadá, že to má hotové - jak se to povedlo? :) @encukou

**Comment by rbas** [comment]
Ahoj, mám to zařídit? Je to easy task, stačilo napsat na podporu ;)
Teda až na tu dokumentaci, tu bych asi hodil na někoho jiného. Věci na serveru za Roští.cz vyřešit můžu.

**Comment by encukou** [comment]
@honzajavorek: pyvo.cz řeší subdomény ve Flasku: https://github.com/pyvec/pyvo.cz/blob/master/pyvocz/views.py#L234

**Comment by honzajavorek** [comment]
@rbas @encukou Jestli to jde ve Flasku tak super, to mi nedošlo. Raději to budu mít v kódu než někde "meta" na sereveru. Teď to stačí jen okopírovat a poslat PR :rocket:

**Comment by honzajavorek** [comment]
Nepovedlo se.

**Comment by honzajavorek** [comment]
@encukou Jak jsi to udělal na tom pyvo.cz? Já tím rozbil celý web :smile:

**Comment by encukou** [comment]
Hmm... Myslím že bylo potřeba nastavit `SERVER_NAME`, dělá to python.cz?
https://github.com/pyvec/pyvo.cz/blob/master/pyvocz/app.py#L25

**Comment by honzajavorek** [comment]
No to mi nefungovalo - koukni jak jsem to mel udelany v
https://github.com/pyvec/python.cz/pull/104

**Comment by honzajavorek** [comment]
Poznámka do budoucna - tak to bylo asi dobře, jen tam byla blbá chyba: https://github.com/pyvec/python.cz/pull/104/files/feff0e2bd9949539526bc3f45ab81b5035577384..881cbea808884d7d8b94742a4b6987b968549b70#r67130589
